spring:
 application:
  name: springboot-rabbitmq

 rabbitmq:
  host: host
  port: 30159
  username: chistory
  password: '!QAZ123'
  virtual-host: test.cs.history
  ssl:
   enabled: true


server:
 port: 8098